globalOptions:
  encoding: utf-8
  logLevel: debug

generate:
  clean: true
  ignoreMissingModels: true
  tsconfigPath: tsconfig.json
  apiItemConfigPath: api.yml
  schemaArgs:
    ref: false,
    required: true

serve:
  host: '127.0.0.1'
  port: 8091
  prefixUrl: /mock
  apiItemConfigPath: api.yml
  optionalsProbability: 0.7
